name: Miscellaneous Tests

on: 
  - push

jobs:
    tests_cubeit:
        runs-on: ubuntu-latest

        steps:
          - name: Chechout repository
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.11'
        
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pytest-playwright

          - name: Ensure browsers are installed
            run: python -m playwright install chromium --with-deps

          - name: Run tests
            run: |
                cd tests_misc
                pytest -v -s *.py

